
/* CONSTRAINT CS_DETALLE_PEDIDO */
ALTER TABLE CS_DETALLE_PEDIDO 
	ADD CONSTRAINT "CS_DETALLE_PEDIDO-id_pedido_fk"  FOREIGN KEY (id_pedido)
	REFERENCES cs_pedidos (id_pedidos) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE CS_DETALLE_PEDIDO 
	ADD CONSTRAINT "CS_DETALLE_PEDIDO-id_producto_fk"  FOREIGN KEY (id_producto)
	REFERENCES cs_producto (id_producto) ON UPDATE NO ACTION ON DELETE NO ACTION;











