
/* CONSTRAINT CS_MOVIMIENTO_STOCK */
ALTER TABLE CS_MOVIMIENTO_STOCK 
	ADD CONSTRAINT "CS_MOVIMIENTO_STOCK-id_producto_fk"  FOREIGN KEY (id_producto)
	REFERENCES cs_producto (id_producto) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE CS_MOVIMIENTO_STOCK 
	ADD CONSTRAINT "CS_MOVIMIENTO_STOCK-id_usuario_fk"  FOREIGN KEY (id_usuario)
	REFERENCES cs_usuario (id_usuario) ON UPDATE NO ACTION ON DELETE NO ACTION;











