
/* CONSTRAINT CS_UTILIZADOR */
ALTER TABLE CS_UTILIZADOR 
	ADD CONSTRAINT "CS_UTILIZADOR-id_cargo_fk"  FOREIGN KEY (id_cargo)
	REFERENCES cs_cargo (id_cargo) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE CS_UTILIZADOR 
	ADD CONSTRAINT "CS_UTILIZADOR-id_empleado_fk"  FOREIGN KEY (id_empleado)
	REFERENCES cs_empleado (id_empleado) ON UPDATE NO ACTION ON DELETE NO ACTION;















