## Entorno de .vscode/settings.json, Ej: rest-client-example.json. 
## Seleccionar entorno con CMD+ALT+E
@SOY_VARIABLE=Soy el contenido

### Categoria listar
curl --location --request POST '{{controlmercaderia_api}}/api/cs/categoria/listar' \
# curl --location --request POST '{{controlmercaderia_api}}/api/cs/categoria/listar/c/cuentaCore' \
--header 'Authorization: Bearer {{controlmercaderia_token}}' \
--header 'xrn-so: web' --header 'xrn-version: 1.0.0' \
--header 'Content-Type: application/json' \
--data-raw '{
    "all": false,
    "page": 1,
    "limit": 10,
    "orderBy": "nombre asc",
    "filterList":[],
    "atributos":"",
    "detalles":[],
    "extra":""
}'
###"filterList":  [{"data":"idCategoria", "op":"eq", "value":100, "group":"and"}]



### Categoria agregar
curl --location --request POST '{{controlmercaderia_api}}/api/cs/categoria/agregar' \
--header 'Authorization: Bearer {{controlmercaderia_token}}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "categoria": "",
	"activo": true,
    "descripcionCategoria": null
}'


### Categoria modificar
curl --location --request POST '{{controlmercaderia_api}}/api/cs/categoria/modificar' \
--header 'Authorization: Bearer {{controlmercaderia_token}}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "idCategoria": 0,
    "categoria": "",
	"activo": true,
    "descripcionCategoria": null
}'


### Categoria eliminar
curl --location --request POST '{{controlmercaderia_api}}/api/zk/usuario/eliminar' \
--header 'Authorization: Bearer {{controlmercaderia_token}}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "idCategoria": 0
}'

// KGC-NOREPLACE-OTROS-INI
// KGC-NOREPLACE-OTROS-FIN
